### ISSUE TITLE
Possible building error:

### ISSUE THREAD

**Issue by JPeisach** [regolith-linux/regolith-i3#13]
Seems like Make is having issues-can't seem to find a solution.

configure: exit 1
dh_auto_configure: cd build && ../configure --build=x86_64-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=\${prefix}/lib/x86_64-linux-gnu --libexecdir=\${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --docdir=/usr/share/doc/regolith-i3-wm --disable-sanitizers returned exit code 1
make[1]: *** [debian/rules:19: override_dh_auto_configure] Error 255
make[1]: Leaving directory '/home/jpeisach/Desktop/Ubuntu i3/regolith-i3-4.16'
make: *** [debian/rules:26: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:

**Comment by kgilmer** [comment]
Hi @ItzSwirlz , nice to see you here.  Your actual build error is likely above these lines, so I don't know what happened.  In any case this repo has been deprecated and I'll mark it as such now.  Regolith now uses "vanilla" i3-gaps, which I also maintain [here](https://github.com/regolith-linux/speed-ricer).

I'm not sure what your goals are but if you're looking to build Regolith from source, have a look at [this repo](https://github.com/regolith-linux/regolith-builder).
