### ISSUE TITLE
i3 msg commands out of order

### ISSUE THREAD

**Issue by downloadpizza** [regolith-linux/regolith-i3#3]
I tried to use `i3-msg 'workspace 3; exec st;workspace 1'` to open a window on workspace 3 and then switch back to 1 (Yes, i can confirm that workspace 3 exists and works, the numbers are just for testing, am going to use $ws1 and so on later)
The problem is that 8n the above, `st` should open in workspace 3, but instead `st` is opened in workspace 1
It also doesn't work in the config file
`exec_always --no-startup-id i3-msg 'workspace 3; exec st;workspace 1'`
It is not related to timing in any way, I tried ```i3-msg 'workspace 3; exec st;workspace 1;workspace 1;workspace 1;workspace 6``` and it still opened on 6 (only that i had like 200 repetitions of workspace 1) If anyone can figure this out, id appreciate it

**Comment by kgilmer** [comment]
Hi @Gabgab2003 , when you say it doesn't work, do you mean there is no change after you run i3-msg, or that st is not being launched in the expected workspace, or something else?

**Comment by downloadpizza** [comment]
@kgilmer As said in last example, it is opened in the last mentioned workspace instead of the chronologicaly correct one

**Comment by downloadpizza** [comment]
e. g. workspace 1;exec ts;workspace 2 should have ws1 opened when exec is called, therefore opening it in ws1. Instead it skips ws1 and opens `st` in ws2

**Comment by downloadpizza** [comment]
@kgilmer once I'm home, I'll try with the unstable build.

**Comment by kgilmer** [comment]
Hi @Gabgab2003 I've made some changes to how workspaces are defined to address an unrelated issue, but this may help you as well: https://github.com/regolith-linux/regolith-i3/commit/68d87b52483e12165b32b70d1c068bc614172474

This change has been pushed to `regolith-stable` so you may be able to address workspaces by ID alone.

**Comment by downloadpizza** [comment]
@kgilmer This also makes the workspaces more accessible to scripts without the $ws# env variables. Good change

**Comment by downloadpizza** [comment]
I can safely say that the original bug described in my first message is something wrong with St and not i3. I3 can execute Firefox on other workspaces just fine

**Comment by downloadpizza** [comment]
@kgilmer Now that I know its not an i3 bug ima close this issue, that alright?

**Comment by kgilmer** [comment]
Sounds good, but I'll do it since I'm here.  Thanks for commenting on the resolution @Gabgab2003 !
