### ISSUE TITLE
toggle vertical/horisontal layout does not work

### ISSUE THREAD

**Issue by kschulz-samsung** [regolith-linux/regolith-i3#4]
the default config contrains $mod+BackSpace to do split toggle, but nothing happens when pressing theis key combo. I looked at the i3 docs and it seems like the format of the command should be bindsys $mod+BackSpace layout split toggle but that does not seem to work either. Other key combos seems to work fine.

**Comment by kgilmer** [comment]
Hmm, odd!  To help narrow down the root-casue, did you install from the LiveCD or PPA?  What version of Ubuntu?  What keyboard layout do you have (US)?

**Comment by kschulz-samsung** [comment]
installed from PPA on Ubuntu 18.04. Keyboard layout is Danish (ISO) but I tried changing they keybinding to $mod+v without any difference.

**Comment by kgilmer** [comment]
You're editing ~/.config/i3-regolith/config?  Are you reloading i3 after
each change?

**Comment by kschulz-samsung** [comment]
yes, I have used i3 previously so I am used to the reload scheme (Also I changed default terminal so I know the reload has been successful)

**Comment by kgilmer** [comment]
Thanks, just asking some sanity questions.  Another one: the layout toggle setting is applied to the _next_ window to be open on the current workspace, so if you're expecting to see a change after toggling between horizontal and vertical, you won't.  When you said "Other key combos seems to work fine." do you mean that other functions (switch workspaces, etc.) work fine, or that using a different key combo (other than BackSpace) to toggle modes works fine?

I would try creating a test user account to try to isolate the issue to either system or user configuration.  All I can think of is if some other program is intercepting the keybinding or that your keymap, being not US, maps the key to another code.  [This section](https://i3wm.org/docs/userguide.html#keybindings) of the i3wm user guide explains how to verify the key mapping to i3 function.

Let me know if any of this helps or changes your situation, and I'll continue to think about what could be wrong and update if anything comes to mind.

**Comment by kschulz-samsung** [comment]
other key combos: toggle fullscreen etc.
I think you found my problem. Back when I had the i3 installed i had a functionality to toggle the layout of the existing containers between vertical and horizontal. I think I mistakenly mixed that up with the one here that just toggles the next opened container.

**Comment by kgilmer** [comment]
Ah, yes you're not the first person to encounter this.  I should have thought of that sooner.  I'll add a thing to the troubleshooting section and close this issue.

**Comment by kgilmer** [comment]
Add this http://regolith-linux.org/troubleshooting.html#layout-keybinding and reworded the section that covers this keybinding in `getting-started` to make it more clear how it's supposed to work.
