### ISSUE TITLE
IRC channel?

### ISSUE THREAD

**Issue by vstath** [regolith-linux/regolith-i3#5]
Hi there, 

just installed and playing with your repository. Thank you for the effort. 

Is there an IRC channel for the community? What's the best way for direct communication between the members of the community?

Again, thanks!

**Comment by kgilmer** [comment]
Hi @vstath !  I do not yet have an IRC channel for Regolith but agree it's a good idea.  I'll update this ticket and the website when I have something in place.  Thanks!

**Comment by kgilmer** [comment]
I was never able to get any word back from the freenode people about creating an official IRC channel.  Maybe I asked the wrong people.  I have been heads down in fixing bugs and trying to make Regolith better for users, and for now want to focus on just the github infrastructure that's already in place.  Of course Issues aren't really designed for general communication.  If anyone would like to setup something for users to communicate, I'm all for it but won't be able to devote the time to it myself, at least in the short term.

**Comment by vstath** [comment]
I believe that chanserv is the way to do so. I have registered it at Freenode. Please get online in order to give you op rights. IRC #regolith-linux @ freenode

I believe you need to have a registered nickname / account with Freenode to become op but I could be wrong.

**Comment by leosunmo** [comment]
Hey @vstath, not quite the same, but there's now a Slack channel where we discuss Dev work as well as user discussion and support. You can sign up at https://regolith-linux.herokuapp.com
