### ISSUE TITLE
wallpaper-change.sh got rrmoved with update

### ISSUE THREAD

**Issue by theScrabi** [regolith-linux/regolith-i3#9]
The last update removed `/usr/bin/wallpaper-change.sh`, however that command is still listed in my config. How am i suposed to update the wallpaper now, or did this command get removed by exident?

**Comment by kgilmer** [comment]
Hi @theScrabi , yes `feh` is no longer being used to handle the wallpapers in Regolith.  Now it's just done via the gnome-control-center.  You can simply remove the lines in your i3 config that deal with walllpaper, or compare yours with what you'll find in `/etc/i3/config`.  You may notice other changes, some bug fixes and additional keybindings requested by users.  Soon another big change will come: migrating the colors to Xresource references.

Sorry for the confusion.  At this time, there is no notification to the user when these updates take effect.

**Comment by theScrabi** [comment]
All right thanks :)
